//
//  HomePresenter.swift
//  Task
//
//  Created by Nrmeen Tomoum on 12/22/18.
//  Copyright (c) 2018 MobileNOC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentStopLoader()
    func presentLoader()
     func presentAlertMessage(message : String)
  func presentListOfServers(response: Home.Server.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentListOfServers(response: Home.Server.Response)
  {
//    let viewModel = Home.Server.ViewModel(name: response.content![0].name, ipAddress: response.ipAddress, deviceIPSubnetMask: <#String#>, status: <#Int#>)
//    viewController?.displayListOfServers(viewModel: [viewModel])
  }
    func presentAlertMessage(message : String)
    {
        viewController?.createAlert(title: "", subTitle: message)
    }
    func presentStopLoader() {
        viewController?.stopIndecator()
    }
    
    func presentLoader() {
        viewController?.displayIndecator()
    }
}
